
#define EVHTP_DISABLE_REGEX
#define EVHTP_DISABLE_EVTHR
#undef EVHTP_DEBUG
#undef EVHTP_DISABLE_SSL
#undef EVHTP_DISABLE_SSL
#undef EVHTP_USE_TCMALLOC
#undef EVHTP_USE_JEMALLOC
#undef EVHTP_USE_TCMALLOC
#undef EVHTP_DISABLE_MEMFUNCTIONS



